apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        env: {{ .Release.Namespace }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: {{ .Release.Name }}-service-key-secret
        - name: ssh-key
          secret:
            secretName: {{ .Release.Name }}-ssh-key-secret
        - name: vpn-settings
          secret:
            secretName: {{ .Release.Name }}-vpn-settings-secret
        - name: env-secrets
          secret:
            secretName: {{ .Release.Name }}-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/startup.sh"]
          args: ["/var/secrets/vpn/ovation.ovpn"]
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: ssh-key
              mountPath: /var/secrets/ssh
            - name: vpn-settings
              mountPath: /var/secrets/vpn
            - name: env-secrets
              mountPath: /var/secrents/env
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: KNOWN_HOSTS_FILE
              value: /var/secrets/ssh/known_hosts
            - name: SSH_KEY_FILE
              value: /var/secrets/ssh/id_rsa
            - name: CLUSTER_HEAD_NODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CLUSTER_HEAD_NODE
            - name: PUBSUB_REQUESTS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PUBSUB_REQUESTS_TOPIC
            - name: PUBSUB_FAILURES_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PUBSUB_FAILURES_TOPIC
            - name: PUBSUB_SUCCESSES_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PUBSUB_SUCCESSES_TOPIC
            - name: PUBSUB_REQUEST_SUBSCRIPTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PUBSUB_REQUEST_SUBSCRIPTION_NAME
            - name: OVATION_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: OVATION_AUTH_DOMAIN
            - name: OVATION_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: OVATION_AUDIENCE
            - name: OVATION_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OVATION_CLIENT_ID
            - name: OVATION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OVATION_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: JWT_SECRET
            - name: SSH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SSH_USERNAME
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
