{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.kubernetes.io/ingress.global-static-ip-name }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Release.Name }}-tls
      hosts:
      {{- range $host := .Values.ingress.hosts }}
        - {{ $host }}
      {{- end -}}
  {{- end -}}
{{- end -}}
