apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpn-settings-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ovation.ovpn: {{ .Values.secret.OVATION_OVPN | b64enc | quote }}
  credentials: {{ .Values.secret.VPN_CREDENTIALS | b64enc | quote }}
