apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  OVATION_CLIENT_ID: {{ .Values.secret.OVATION_CLIENT_ID  | b64enc | quote }}
  OVATION_CLIENT_SECRET: {{ .Values.secret.OVATION_CLIENT_SECRET  | b64enc | quote }}


