apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
type: Opaque
data:
  OVATION_CLIENT_ID: {{ .Values.secret.OVATION_CLIENT_ID  | b64enc | quote }}
  OVATION_CLIENT_SECRET: {{ .Values.secret.OVATION_CLIENT_SECRET  | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.OVATION_JWT_SECRET | b64enc | quote }}
  SSH_USERNAME: {{ .Values.secret.SSH_USERNAME | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpn-settings-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
type: Opaque
data:
  ovation.ovpn: {{ .Values.secret.OVATION_OVPN | quote }}
  credentials: {{ .Values.secret.VPN_CREDENTIALS | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
type: Opaque
data:
  id_rsa: {{ .Values.secret.SSH_ID_RSA | b64enc | quote }}
  id_rsa.pub: {{ .Values.secret.SSH_ID_RSA_PUB | b64enc | quote }}
  known_hosts: {{ .Values.secret.SSH_KNOWN_HOSTS | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
type: Opaque
data:
  key.json: {{ .Values.secret.GCP_SERVICE_KEY_JSON | b64enc | quote }}
