FROM ubuntu:16.04

RUN apt-get update -y
RUN apt-get install -y wget

RUN wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
RUN apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9

RUN apt-get update -y
RUN apt-get install -y singularity-container
